<header>
      <!-- nav bar for the web -->
    <nav class="navbar">
          <!-- web logo -->
        <a class="navbar_brand" href="index.php">
          <img src="styles/images/Bookicon.png" alt="Logo" class="logo_image">
        </a>
        <!-- nav section -->
        <div class="collapse navbar_collapse" id="navbarNav">
          <ul>
            <li class="nav_item">
              <a class="nav-link" href="product.php">Main Products</a>
            </li>
            <li class="nav_item">
              <a class="nav-link" href="enquire.php">Enquire</a>
            </li>
            <li class="nav_item">
              <a class="nav-link" href="about.php">About Me</a>
            </li>
            <li class="nav_item">
              <a class="nav-link" href="enhancements.php">Enhancements</a>
            </li>
          </ul>
          <!-- search bar -->
          <form class="form_inline">
            <input class="form_control" type="search" placeholder="Search" aria-label="Search" >
          </form>
        </div>
      
    </nav>
  </header>