<!-- nav section -->
        <div class="collapse navbar_collapse" id="navbarNav">
          <ul>
            <li class="nav_item">
              <a class="nav-link" href="product.php">Main Products</a>
            </li>
            <li class="nav_item">
              <a class="nav-link" href="payment.php">Payment</a>
            </li>
            <li class="nav_item">
              <a class="nav-link" href="about.php">About Me</a>
            </li>
            <li class="nav_item">
              <a class="nav-link" href="manager.php">Manager</a>
            <li class="nav_item">
              <a class="nav-link" href="enhancements.php">Enhancements</a>
            </li>
          </ul>